services:
  - type: web
    name: nexsync-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
